Fix missing escape of '%' in jsonnet
dNationCloud/kubernetes-monitoring pull request #42
Opened 2021-02-03 16:09 UTC by jurslo

Signed-off-by: Juraj Sloboda <juraj.sloboda@x-works.io>

2021-02-04 07:28 UTC, matofeder approved these changes

2021-02-04 07:30 UTC, matofeder requested changes
Please investigate why pipeline failed:
```
Error: Command failed: rm -rf "/home/runner/work/kubernetes-monitoring/kubernetes-monitoring/chart"
rm: cannot remove '/home/runner/work/kubernetes-monitoring/kubernetes-monitoring/chart/charts/dnation-kubernetes-jsonnet-translator-0.1.2.tgz': Permission denied
```

2021-02-04 09:28 UTC, davidsuba commented
> Please investigate why pipeline failed:
> 
> ```
> Error: Command failed: rm -rf "/home/runner/work/kubernetes-monitoring/kubernetes-monitoring/chart"
> rm: cannot remove '/home/runner/work/kubernetes-monitoring/kubernetes-monitoring/chart/charts/dnation-kubernetes-jsonnet-translator-0.1.2.tgz': Permission denied
> ```

Problem was `checkout` after `helm/chart-testing-action`, which run in docker as root and therefore `checkout` cannot delete its files. 
Solution: move `linting appVersion` to separate job. [PR](#44) .

2021-02-04 09:28 UTC, davidsuba approved these changes

2021-02-05 08:40 UTC, matofeder approved these changes

2021-02-05 08:43 UTC, merged